# -*- coding: utf-8 -*-
"""menahil.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bq9XPRKDkwxnHXrZey1WSDEgHuVH1c5I
"""

print("Menahil Fatima")